CREATE TABLE `ventas2` (
  `Id_venta` int(11) DEFAULT NULL,
  `plaza` text,
  `proyecto` text,
  `etapa` text,
  `fecha_venta` datetime DEFAULT NULL,
  `fecha_firma` datetime DEFAULT NULL,
  `id_cliente` int(11) DEFAULT NULL,
  `nombre` text,
  `manzana` int(11) DEFAULT NULL,
  `lote` int(11) DEFAULT NULL,
  `prototipo` text,
  `vts` text,
  `avance` text,
  `enganche` int(11) DEFAULT NULL,
  `precio` int(11) DEFAULT NULL,
  `m2` double DEFAULT NULL,
  `cobrado` double DEFAULT NULL,
  `vendedor` text,
  `cajon` text,
  `tipo` text,
  `vc` text,
  `estado` text,
  `fuente` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;